import { describe, it, expect } from "vitest";
import { extractPdfText } from "../lib/ingest.js";

/**
 * Minimal valid PDF containing "Milchleistung 1234", generated by fpdf2.
 * Stored as base64 so no binary fixture file is needed.
 */
const FIXTURE_PDF_B64 =
  "JVBERi0xLjMKJenr8b8KMSAwIG9iago8PAovQ291bnQgMQovS2lkcyBbMyAwIFJdCi9NZWRpYUJveCBbMCAwIDU5NS4yOCA4NDEuODldCi9UeXBlIC9QYWdlcwo+PgplbmRvYmoKMiAwIG9iago8PAovT3BlbkFjdGlvbiBbMyAwIFIgL0ZpdEggbnVsbF0KL1BhZ2VMYXlvdXQgL09uZUNvbHVtbgovUGFnZXMgMSAwIFIKL1R5cGUgL0NhdGFsb2cKPj4KZW5kb2JqCjMgMCBvYmoKPDwKL0NvbnRlbnRzIDQgMCBSCi9QYXJlbnQgMSAwIFIKL1Jlc291cmNlcyA2IDAgUgovVHlwZSAvUGFnZQo+PgplbmRvYmoKNCAwIG9iago8PAovRmlsdGVyIC9GbGF0ZURlY29kZQovTGVuZ3RoIDc5Cj4+CnN0cmVhbQp4nDNS8OIy0DM1VyjncgpR0HczVDA00jMwUAhJU3ANAQkZG+oZWiiYW5rqmZsrhKQoaPhm5iRn5KRmFpeU5qUDVRubaCqEZIFUAwCJ8RJaCmVuZHN0cmVhbQplbmRvYmoKNSAwIG9iago8PAovQmFzZUZvbnQgL0hlbHZldGljYQovRW5jb2RpbmcgL1dpbkFuc2lFbmNvZGluZwovU3VidHlwZSAvVHlwZTEKL1R5cGUgL0ZvbnQKPj4KZW5kb2JqCjYgMCBvYmoKPDwKL0ZvbnQgPDwvRjEgNSAwIFI+PgovUHJvY1NldCBbL1BERiAvVGV4dCAvSW1hZ2VCIC9JbWFnZUMgL0ltYWdlSV0KPj4KZW5kb2JqCjcgMCBvYmoKPDwKL0NyZWF0aW9uRGF0ZSAoRDoyMDI2MDYxODE0MTcwNlopCj4+CmVuZG9iagp4cmVmCjAgOAowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwMTUgMDAwMDAgbiAKMDAwMDAwMDEwMiAwMDAwMCBuIAowMDAwMDAwMjA1IDAwMDAwIG4gCjAwMDAwMDAyODUgMDAwMDAgbiAKMDAwMDAwMDQzNSAwMDAwMCBuIAowMDAwMDAwNTMyIDAwMDAwIG4gCjAwMDAwMDA2MTkgMDAwMDAgbiAKdHJhaWxlcgo8PAovU2l6ZSA4Ci9Sb290IDIgMCBSCi9JbmZvIDcgMCBSCi9JRCBbPDU2QTREMDJCMDdCRDhFRkFFMDg5MjM4NDg0NDkxNkJCPjw1NkE0RDAyQjA3QkQ4RUZBRTA4OTIzODQ4NDQ5MTZCQj5dCj4+CnN0YXJ0eHJlZgo2NzQKJSVFT0YK";

describe("extractPdfText (production implementation from ingest.ts)", () => {
  it("gibt einen nicht-leeren String aus einem echten PDF-Buffer zurück", async () => {
    const buf = Buffer.from(FIXTURE_PDF_B64, "base64");
    const text = await extractPdfText(buf);
    expect(text.length).toBeGreaterThan(0);
  });

  it("enthält den bekannten Text aus der Fixture-PDF", async () => {
    const buf = Buffer.from(FIXTURE_PDF_B64, "base64");
    const text = await extractPdfText(buf);
    expect(text).toContain("Milchleistung");
    expect(text).toContain("1234");
  });

  it("wirft bei einem ungültigen PDF-Buffer einen Fehler", async () => {
    const garbage = Buffer.from("this is not a pdf");
    await expect(extractPdfText(garbage)).rejects.toThrow();
  });
});
