const colors = {
  light: {
    text: "#1a1b2e",
    tint: "#3b82f6",
    background: "#f8f9ff",
    foreground: "#1a1b2e",
    card: "#ffffff",
    cardForeground: "#1a1b2e",
    primary: "#3b82f6",
    primaryForeground: "#ffffff",
    secondary: "#f0f2f8",
    secondaryForeground: "#1a1b2e",
    muted: "#f0f2f8",
    mutedForeground: "#6b7280",
    accent: "#f59e0b",
    accentForeground: "#1a1b2e",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e2e4ee",
    input: "#e2e4ee",
    userBubble: "#3b82f6",
    userBubbleForeground: "#ffffff",
    assistantBubble: "#f0f2f8",
    assistantBubbleForeground: "#1a1b2e",
  },
  dark: {
    text: "#f0f0f4",
    tint: "#3b82f6",
    background: "#1a1b2e",
    foreground: "#f0f0f4",
    card: "#242537",
    cardForeground: "#f0f0f4",
    primary: "#3b82f6",
    primaryForeground: "#ffffff",
    secondary: "#2d2f45",
    secondaryForeground: "#f0f0f4",
    muted: "#2d2f45",
    mutedForeground: "#9ca3af",
    accent: "#f59e0b",
    accentForeground: "#1a1b2e",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#3d3f55",
    input: "#3d3f55",
    userBubble: "#3b82f6",
    userBubbleForeground: "#ffffff",
    assistantBubble: "#2d2f45",
    assistantBubbleForeground: "#f0f0f4",
  },
  radius: 12,
};

export default colors;
