import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import meRouter from "./me";
import datasetsRouter from "./datasets";
import filesRouter from "./files";
import analysesRouter from "./analyses";
import rulesRouter from "./rules";
import warningsRouter from "./warnings";
import reportsRouter from "./reports";
import masterdataRouter from "./masterdata";
import adminRouter from "./admin";
import privacyRouter from "./privacy";
import { knowledgeRouter } from "./knowledge";
import templatesRouter from "./templates";
import publicRouter from "./public";
import checkoutRouter from "./checkout";
import billingRouter from "./billing";
import teamRouter from "./team";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(meRouter);
router.use(datasetsRouter);
router.use(filesRouter);
router.use(analysesRouter);
router.use(rulesRouter);
router.use(warningsRouter);
router.use(reportsRouter);
router.use(masterdataRouter);
router.use(adminRouter);
router.use(privacyRouter);
router.use(knowledgeRouter);
router.use(templatesRouter);
router.use(publicRouter);
router.use(checkoutRouter);
router.use(billingRouter);
router.use(teamRouter);

export default router;
