// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bovial-mobile/ChatScreen.tsx": () => import("../components/mockups/bovial-mobile/ChatScreen.tsx"),
  "./components/mockups/bovial-mobile/HomeScreen.tsx": () => import("../components/mockups/bovial-mobile/HomeScreen.tsx"),
  "./components/mockups/bovial-mobile/ResultScreen.tsx": () => import("../components/mockups/bovial-mobile/ResultScreen.tsx")
};
